title: Huanghaizhaoyang
page-top-title: Huanghaizhaoyang
top-section-bg-text: Be what you wanna be
home-subtitle: Huanghaizhaoyang&ensp;|&ensp;黄海朝阳
copyright-text: '&copy; Huanghaizhaoyang 2018-2025. All Rights Reserved.'
